version: '3'
services:

  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
    ports:
      - "3306:3306"
    volumes:
      - ./data/sql:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      - DJANGO_DEBUG=true
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start
